# Teacher Model Configuration

model:
  name: "unsloth/Qwen2-VL-7B-Instruct"
  max_seq_length: 2048
  load_in_4bit: true

lora:
  r: 32
  lora_alpha: 32
  lora_dropout: 0
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"

image_processor:
  max_pixels: 256 * 28 * 28
  min_pixels: 128 * 28 * 28

training:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  warmup_steps: 10
  num_train_epochs: 3
  learning_rate: 1e-5
  bf16: true
  fp16: false
  optim: "adamw_8bit"
  logging_steps: 1
  save_steps: 200
  save_total_limit: 2
  output_dir: "outputs-7B"

data:
  train_path: "data/vlsp2023_train_data.json"
  train_images: "data/training-images"
  dev_path: "data/vlsp2023_dev_data.json"
  dev_images: "data/dev-images"